version: '3.8'

services:
  web:
    build: ./django_project
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/static
      - ./django_project/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
        - static_volume:/static
    depends_on:
      - web
  postgres:
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:

